# Generated by Django 3.1 on 2020-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_userdetails_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
