# Generated by Django 3.1 on 2020-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_auto_20200818_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='phone',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='category',
            field=models.CharField(default='super hero', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ref',
            field=models.CharField(default='www.google.com', max_length=200),
            preserve_default=False,
        ),
    ]
