# Generated by Django 3.1 on 2020-08-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0004_auto_20200818_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
