# Generated by Django 3.1 on 2020-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0005_auto_20200818_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
